In [17]:
import pandas as pd

In [18]:
pd.read_csv('train2024.csv', sep = ';', index_col=0)

,texto,aspect,polarity,start_position,end_position
id,,,,,
3,- Serviço de recepção muito ruim a noite; - Ac...,colchão,-1,85,92
4,- Serviço de recepção muito ruim a noite; - Ac...,recepção,-1,13,21
5,- Serviço de recepção muito ruim a noite; - Ac...,serviço,-1,2,9
43,"A localização é ótima, dá para ir a pé em vári...",hotel,1,148,153
44,"A localização é ótima, dá para ir a pé em vári...",cama,-1,369,373
...,...,...,...,...,...
4430,Já é a terceira vez que me hospedo no Expressi...,atendimento,1,352,363
4431,"O hotel é um pouco antigo, mas bem aconchegant...",café da manhã,1,49,62
4432,"Estive em novembro/2010, por 6 dias, hospedada...",quarto,0,292,298
4433,"excelente cafe da manha,muito limpo,otimo aten...",atendimento,1,42,53
4434,"O hotel é um pouco antigo, mas bem aconchegant...",praia,0,289,294

In [21]:
pd.read_csv('task1_test.csv', sep = ';', index_col=0)

                                                  texto
id
2     - Não tem Wi-Fi como mencionado no site - Frig...
6     1) A temperatura da água ficava variando entre...
21    A ESTADIA DOS PAXS FORAM PESSIMAS. UM DOS QUAR...
9     A boa localização é um ponto forte, próximo ao...
18    A cadeia Ibis é o Mc Donalds dos hotéis; não é...
...                                                 ...
1545  meu quarto estava sujo.. tinha um copo descart...
1757  o hotel Berthier Porte de Clichy, apesar de pe...
2235  passei 3 noites nesse hotel, o hotél e grande ...
2256  péssimo Staff fraco café da manhã  bairro de i...
469   É a segunda vez que fico nesse hotel. Muito bo...

[283 rows x 1 columns]

In [22]:
pd.read_csv('task2_test.csv', sep = ';', index_col=0)

,texto,aspect,start_position,end_position
id,,,,
1461,Lemos as avaliações antes da viajem e ficamos ...,localização,356,367
2041,"O Hotel está bem sitiado, dado que é uma zona ...",limpeza,312,319
1058,"Hotel bem localizado com metro na esquina, fun...",funcionários,43,55
93,"A pirâmide de 30 andares, com a esfinge de ent...",quarto,417,423
945,Fraquíssima opção em NY. Há certamente melhore...,preço,59,64
...,...,...,...,...
2135,O hotel Ibis é de qualidade inferior ao que es...,casal,143,148
1401,ibis abaixo da crítica e muito fora do padrão ...,cidade,83,89
1083,"Hotel bem localizado, de fácil acesso, a meia ...",internet,150,158
1824,"O hotel é bem localizado e central, o atendime...",preço,183,188
1393,Hotel velho e mal frequentado. Os quartos não ...,família,167,174